name: Actions Workflow

on: 
  push:
  pull_request:
    types: [opened, reopened, assigned]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List repo files
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REPOSITORY
          echo "${{ github.token }}"
      - name: checkout repo files
        uses: actions/checkout@v1
      - name: after checkout
        run: |
          pwd
          ls -al
      - name: Simple JS actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: testing
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"