name: container

on: push

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image:  node:16-alpine3.12
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
